### ISSUE TITLE
Purge GNOME desktop environment w/ remove_cups_packages

### ISSUE THREAD

**Issue by derogab** [Turtlecute33/Hardening-linux-script#3]
The `remove_cups_packages` function causes a complete purge of GNOME desktop environment in Debian 12.7.

The problem seems to be caused by [these lines](https://github.com/Turtlecute33/Hardening-linux-script/blob/68280f0f12922df8639c93c7f83d84e11e88ffa5/hardening-script.sh#L69C7-L73C9):
```bash
cups_packages=$(dpkg -l | grep 'cups' | awk '{print $2}')
if [ -n "$cups_packages" ]; then
  package_count=$(echo "$cups_packages" | wc -l)
  apt-get purge -y $cups_packages >/dev/null 2>&1
fi
```
The removal of packages `cups-pk-helper` and `libcups2` causes the complete removal of desktop environment.

**Comment by Turtlecute33** [comment]
I should have fixed the issue, now the script removes all the cups related packages but `cups-pk-helper` and `libcups2` are whitelisted. Can you kindly test it? i don't have a working ubuntu machine with GNOME installed

**Comment by derogab** [comment]
Just executed the script again and I still have my GNOME. It seems that the workaround works well :)
